[server]
runOnSave = true
fileWatcherType = "auto"
enableXsrfProtection = true

[theme]
base="light"
primaryColor="#000060"
secondaryBackgroundColor= "#ffffff"

[client]
showErrorDetails = false

[runner]
fastReruns = true

[browser]
gatherUsageStats = true
